parameters:
  buildConfiguration: 'Release'

steps:
- script: 'echo "Hi Jon! From the build-pipeline branch - $(Build.DefinitionName), ${{ parameters.buildConfiguration }}, $(Build.SourceBranch), $(Build.SourceBranchName),  $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
  displayName: 'Write build info from template'
  workingDirectory: $(wwwrootDir)

- task: DotNetCoreCLI@2
  displayName: 'Build the project - ${{ parameters.buildConfiguration }}'
  inputs:
    command: 'build'
    arguments: '--no-restore --configuration ${{ parameters.buildConfiguration }}'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Publish the project - ${{ parameters.buildConfiguration }}'
  inputs:
    command: 'publish'
    projects: '**/*.csproj'
    publishWebProjects: false
    arguments: '--no-build --configuration ${{ parameters.buildConfiguration }} --output $(Build.ArtifactStagingDirectory)/$(Build.SourceBranchName)/${{ parameters.BuildConfiguration }}'
    zipAfterPublish: true